POST http://localhost:3000/create_user
Content-Type: application/json

{
  "full_name": "Ceaser Doe",
  "mob_num": "+911234567892",
  "pan_num": "abcde1236f",
  "manager_id": 3
}
###

POST http://localhost:3000/get_users
Content-Type: application/json

{
  "user_id": "42677e14-7e7b-4008-a8a8-aae0b0b332e8",
  "mob_num": "1234567890",
  "manager_id": 1
}
###

POST http://localhost:3000/delete_user
Content-Type: application/json

{
  "user_id": "7d5d4c63-a979-43a5-a030-ea16b33637ff",
  "mob_num": "1234567893"

}
###

POST http://localhost:3000/update_user
Content-Type: application/json

{
   "user_ids": ["e7a75956-99b1-4841-a421-e8fe2956ea37","39e248d5-c7da-4ace-940e-3723fbecc1fc"],
  "update_data": {
    "full_name": "Ceaser Doe",
    "mob_num": "+911234567892",
    "pan_num": "abcde1236f",
    "manager_id": 3
  }
}
###